https://github.com/kris-nader/scTherapy

r-base

In [1]:
# # Install packages if you haven't already
# install.packages("readxl")

# # Load the libraries
# library(readxl)

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

for the integrated dataset of all samples

In [1]:
my_data <- read.csv("malignant_cells_DEG_all_samples.csv", row.names = 1)
saveRDS(my_data, file = "malignant_cells_DEG_all_samples.RDS")

In [2]:
# load data
malignant_cells_DEG <- readRDS("malignant_cells_DEG_all_samples.RDS")

head(malignant_cells_DEG)
#           avg_log2FC    p_val_adj
# LYZ       5.254787      1.512117e-107
# S100A9    4.530434      9.073954e-39
# 	         .............
# IL32 	   -3.599663      3.197208e-164
# GNLY     -4.417322      8.259763e-81

       avg_log2FC p_val_adj
CASC15 5.694498   0
SOX4   5.247437   0
GNAQ   3.113246   0
SSBP2  3.817840   0
CDK6   3.808591   0
MED13L 2.274940   0

In [8]:
install.packages(c("dplyr", "logger", "httr", "jsonlite", "readr"))

also installing the dependencies ‘progress’, ‘cpp11’, ‘vctrs’, ‘hms’, ‘vroom’, ‘tzdb’


Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [3]:
# load libraries
invisible(lapply(c("dplyr","logger","httr", "jsonlite", "readr"), library, character.only = !0));
invisible(source("https://raw.githubusercontent.com/kris-nader/scTherapy/main/R/predict_compounds.R"))

# load data for making drug:dose predictions
gene_list <- "https://raw.githubusercontent.com/kris-nader/scTherapy/main/geneinfo_beta_input.txt"
gene_info <- data.table::fread(gene_list) %>% as.data.frame()

# filter DEG
DEG_malignant <- malignant_cells_DEG %>%
  mutate(gene_symbol = rownames(.)) %>% inner_join(gene_info, by = "gene_symbol") %>%
  filter((p_val_adj <= 0.05 & (avg_log2FC > 1 | avg_log2FC < -1)) | (avg_log2FC > -0.1 & avg_log2FC < 0.1))
DEG_malignant_list <- setNames(as.list(DEG_malignant$avg_log2FC), DEG_malignant$gene_symbol)

#predict monotherapies for malignant cluster
monotherapy_drugs <- predict_drugs(DEG_malignant_list)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [4]:
monotherapy_drugs

   cid       Drug_Name         Response
1    6918837 panobinostat      High
2  135564985 ganetespib        High-to-moderate
3    6505803 tanespimycin      High-to-moderate
4   53358942 idasanutlin       High-to-moderate
5   11364421 BI-2536           High-to-moderate
6      30323 daunorubicin      High-to-moderate
7    6914657 FK-866            High-to-moderate
8   25227462 PF-03758309       High-to-moderate
9   24800541 delanzomib        High-to-moderate
10  25183872 ixazomib          High-to-moderate
11    104842 SN-38             High-to-moderate
12     24360 camptothecin      High-to-moderate
13     41867 epirubicin        High-to-moderate
14      4122 nocodazole        High-to-moderate
15     26596 parbendazole      High-to-moderate
19  46885626 GSK1070916        Moderate
20  24771867 alisertib         Moderate
21  11442891 danusertib        Moderate
22  11152667 AZD7762           Moderate
23  71496458 osimertinib       Moderate
24  25257557 CX-5461           Moderate
25  49836020 birinapant        Moderate
26   9936746 OTX015            Moderate
27    446541 mycophenolic-acid Moderate
28    108143 tamibarotene      Moderate
29     36462 etoposide         Moderate
   MoA                                                        Dose.nM.
1  HDAC_inhibitor                                              730.0000
2  -                                                           622.4787
3  HSP_inhibitor                                               281.4812
4  MDM_inhibitor                                               438.7463
5  PLK_inhibitor                                               498.9539
6  RNA_synthesis_inhibitor_topoisomerase_inhibitor            1000.0000
7  niacinamide_phosphoribosyltransferase_inhibitor             389.5792
8  p21_activated_kinase_inhibitor                              483.1389
9  proteasome_inhibitor                                        240.5565
10 proteasome_inhibitor                                        924.4444
11 topoisomerase_inhibitor                                     492.3077
12 topoisomerase_inhibitor                                     433.3330
13 topoisomerase_inhibitor                                     865.0000
14 tubulin_polymerization_inhibitor                           1000.0000
15 tubulin_polymerization_inhibitor                            592.5924
19 Aurora_kinase_inhibitor                                     351.6185
20 Aurora_kinase_inhibitor                                    1000.0000
21 Aurora_kinase_inhibitor_growth_factor_receptor_inhibitor    146.6676
22 CHK_inhibitor                                               188.7938
23 EGFR_inhibitor                                             1000.0000
24 RNA_polymerase_inhibitor                                    410.1895
25 XIAP_inhibitor                                              208.1480
26 bromodomain_inhibitor                                       220.0000
27 dehydrogenase_inhibitor_inositol_monophosphatase_inhibitor  378.1480
28 retinoid_receptor_agonist                                   924.4480
29 topoisomerase_inhibitor                                     474.0738
   Toxicity
1  Potentially toxic (low confidence)
2  Potentially toxic (low confidence)
3
4
5
6
7
8  Potentially toxic (low confidence)
9  Potentially toxic (low confidence)
10
11 Potentially toxic (low confidence)
12
13 Potentially toxic (low confidence)
14
15
19
20
21
22
23
24
25
26
27
28
29

In [5]:
write.csv(monotherapy_drugs, "scTherapy_monotherapy_drugs_all_samples2.csv", row.names = TRUE)

install.packages("writexl")   
library(writexl)
writexl::write_xlsx(monotherapy_drugs, "scTherapy_monotherapy_drugs_all_samples2.xlsx")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

per each sample

In [7]:
samples <- c("ak", "az", "b", "v", "ts")

invisible(lapply(c("dplyr","logger","httr", "jsonlite", "readr"), library, character.only = !0))
invisible(source("https://raw.githubusercontent.com/kris-nader/scTherapy/main/R/predict_compounds.R"))

gene_list <- "https://raw.githubusercontent.com/kris-nader/scTherapy/main/geneinfo_beta_input.txt"
gene_info <- data.table::fread(gene_list) %>% as.data.frame()

library(writexl)

for (sample in samples) {
  input_csv <- paste0("malignant_cells_DEG_", sample, "_tcells.csv")
  my_data <- read.csv(input_csv, row.names = 1)
  saveRDS(my_data, file = paste0("malignant_cells_DEG_", sample, "_tcells.RDS"))
  
  malignant_cells_DEG <- my_data
  
  DEG_malignant <- malignant_cells_DEG %>%
    mutate(gene_symbol = rownames(.)) %>%
    inner_join(gene_info, by = "gene_symbol") %>%
    filter((p_val_adj <= 0.05 & (avg_log2FC > 1 | avg_log2FC < -1)) | (avg_log2FC > -0.1 & avg_log2FC < 0.1))
  
  DEG_malignant_list <- setNames(as.list(DEG_malignant$avg_log2FC), DEG_malignant$gene_symbol)
  monotherapy_drugs <- predict_drugs(DEG_malignant_list)
  
  write.csv(monotherapy_drugs, file = paste0("scTherapy_monotherapy_drugs_", sample, ".csv"), row.names = TRUE)
  write_xlsx(monotherapy_drugs, path = paste0("scTherapy_monotherapy_drugs_", sample, ".xlsx"))
}